"""add style_config to layers

Revision ID: 209ff4ccc05a
Revises: 6c0edf9359e2
Create Date: 2026-08-04 22:18:38.709257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '209ff4ccc05a'
down_revision: Union[str, None] = '6c0edf9359e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
