"""add style_config to layers

Revision ID: 4c391ff4cc8c
Revises: c38f9fa59655
Create Date: 2026-08-05 09:47:00.514158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4c391ff4cc8c'
down_revision: Union[str, None] = 'c38f9fa59655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
