"""add style_config to layers

Revision ID: 4ec7d19fd16e
Revises: 0003
Create Date: 2026-07-31 22:47:43.790283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '4ec7d19fd16e'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('features_layer_id_fkey', 'features', type_='foreignkey')
    op.create_foreign_key(None, 'features', 'layers', ['layer_id'], ['id'])
    op.add_column('layers', sa.Column('style_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('layers', 'style_config')
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.create_foreign_key('features_layer_id_fkey', 'features', 'layers', ['layer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
