"""add style_config to layers

Revision ID: 7fd30ec7ffd6
Revises: 82ce0da08c28
Create Date: 2026-08-05 21:41:28.728656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '7fd30ec7ffd6'
down_revision: Union[str, None] = '82ce0da08c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
